### ISSUE TITLE
"tests" is installed as a site-package after installation of dmiparser in the toolchain

### ISSUE THREAD

**Issue by mszpala** [Arondight/python-dmiparser#1]
It seems that dmiparser creates two packages in the toolchain - `dmiparser` and `tests`.
This can be clearly seen once there's attempt to uninstall dmiparser from toolchain, see the log below:
```
Found existing installation: dmiparser 5.0
Uninstalling dmiparser-5.0:
  Would remove:
    virtualenvs/test1111/bin/dmidecoder
    virtualenvs/test1111/bin/dmiparser
    virtualenvs/test1111/lib/python3.11/site-packages/dmiparser-5.0.dist-info/*
    virtualenvs/test1111/lib/python3.11/site-packages/dmiparser/*
    virtualenvs/test1111/lib/python3.11/site-packages/tests/*
```

The existence of `tests` as site package could influence imports, especially for test suites written in Python where `import tests.something` could be used.

I know that last change was made 2 years ago, but maybe there's chance to fix it. Thanks in advance!

**Comment by Arondight** [comment]
thank you and i will do it
